# Define the base image
FROM node:18.14.0-alpine

# Create a working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install the dependencies
RUN npm ci \
 && chown -R $(id -u):$(id -g) node_modules # workaround for https://github.com/npm/cli/issues/5900

# Copy the rest of the project files
COPY . .

# Run tests
RUN npm run test

# Build the Next.js application
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Start the application
CMD ["npm", "start"]