import "./globals.css";
import type { Metadata } from "next";
import Providers from "@/app/providers";
import { bookmanOldStyle, franklinGothic } from "@/commons/assets/fonts/fonts";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="dark">
            <body
                className={`${franklinGothic.variable} ${bookmanOldStyle.variable} font-sans`}
            >
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
